sudo: required
services:
  - docker

# Build the tests for the client
before_install:
  - docker build -t drkostas/react-test -f ./client/Dockerfile.dev ./client

# Run the tests for the client
script:
  # the `-- --coverage` triggers the test to exit after finishing (with exit code)
  - docker run drkostas/react-test npm run test -- --coverage

# Build all the production versions
after_success:
  - docker build -t drkostas/multi-client ./client
  - docker build -t drkostas/multi-nginx ./nginx
  - docker build -t drkostas/multi-server ./server
  - docker build -t drkostas/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push drkostas/multi-client
  - docker push drkostas/multi-nginx
  - docker push drkostas/multi-server
  - docker push drkostas/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker-course"
  env: "MultiDockerCourse-env"
  bucket_name: "elasticbeanstalk-us-east-2-844347551258"
  bucket_path: "docker-multi-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"